package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class CheckSymptomaticTrigger_c_0Signal extends ActorTypeSignal {
  public CheckSymptomaticTrigger_c_0Signal() {
    this.setName("CheckSymptomaticTrigger_c_0");
    this.setDescription("h");
    this.AddActor("TriageNurse");
  }

}
