package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class SuitableforAdmissionTrigger_aSignal extends ActorTypeSignal {
  public SuitableforAdmissionTrigger_aSignal() {
    this.setName("SuitableforAdmissionTrigger_a");
    this.setDescription("SecondPlaceholderSignal");
    this.AddActor("Doctor");
  }

}
