package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.basicStructures.RoomType;

public class Radiology extends RoomType {
  private static Radiology instance;

  private Radiology() {
    super();
  }

  public static RoomType getInstance() {
    if (instance == null) {
      instance = new Radiology();
    }
    return instance;
  }
}
