package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class placeholderNameSignal extends ActorTypeSignal {
  public placeholderNameSignal() {
    this.setName("placeholderName");
    this.setDescription("n");
  }

}
