package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class LFTTrigger_bSignal extends ActorTypeSignal {
  public LFTTrigger_bSignal() {
    this.setName("LFTTrigger_b");
    this.setDescription("h");
    this.AddActor("CubicleNurse");
  }

}
