package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class AdmittononrespiratoryTrigger_a8Signal extends ActorTypeSignal {
  public AdmittononrespiratoryTrigger_a8Signal() {
    this.setName("AdmittononrespiratoryTrigger_a8");
    this.setDescription("h");
    this.AddActor("Doctor");
  }

}
