package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class PatientArrivesTrigger_fSignal extends ActorTypeSignal {
  public PatientArrivesTrigger_fSignal() {
    this.setName("PatientArrivesTrigger_f");
    this.setDescription("SecondPlaceholderSignal");
    this.AddActor("TriageNurse");
  }

}
