package AgentLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class AggregateAttributeMonitor_Constraints extends BaseConstraintsDescriptor {
  public AggregateAttributeMonitor_Constraints() {
    super(CONCEPTS.AggregateAttributeMonitor$nr);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept AggregateAttributeMonitor$nr = MetaAdapterFactory.getConcept(0x7dcff301ba01414eL, 0x8574a8f6da31876bL, 0x6ca3e29db4287123L, "AgentLanguage.structure.AggregateAttributeMonitor");
  }
}
