package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class AdmittoSRTrigger_b7_0Signal extends ActorTypeSignal {
  public AdmittoSRTrigger_b7_0Signal() {
    this.setName("AdmittoSRTrigger_b7_0");
    this.setDescription("h");
    this.AddActor("Doctor");
  }

}
