package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class AdmissionTriageTrigger_dSignal extends ActorTypeSignal {
  public AdmissionTriageTrigger_dSignal() {
    this.setName("AdmissionTriageTrigger_d");
    this.setDescription("SecondPlaceholderSignal");
    this.AddActor("PreAdmissionStaff");
  }

}
