package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class ConfirmwithPCRTrigger_d3_0Signal extends ActorTypeSignal {
  public ConfirmwithPCRTrigger_d3_0Signal() {
    this.setName("ConfirmwithPCRTrigger_d3_0");
    this.setDescription("h");
    this.AddActor("CubicleNurse");
  }

}
