package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class DischargeTrigger_a1_8Signal extends ActorTypeSignal {
  public DischargeTrigger_a1_8Signal() {
    this.setName("DischargeTrigger_a1_8");
    this.setDescription("h");
    this.AddActor("WardStaff");
  }

}
