package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class DoPCRTrigger_a3_2Signal extends ActorTypeSignal {
  public DoPCRTrigger_a3_2Signal() {
    this.setName("DoPCRTrigger_a3_2");
    this.setDescription("h");
    this.AddActor("WardStaff");
  }

}
