package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class IsolationPeriodTrigger_a0_0Signal extends ActorTypeSignal {
  public IsolationPeriodTrigger_a0_0Signal() {
    this.setName("IsolationPeriodTrigger_a0_0");
    this.setDescription("h");
    this.AddActor("PreAdmissionStaff");
  }

}
