package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class PreAdmissionTriageTrigger_b_0Signal extends ActorTypeSignal {
  public PreAdmissionTriageTrigger_b_0Signal() {
    this.setName("PreAdmissionTriageTrigger_b_0");
    this.setDescription("h");
    this.AddActor("PreAdmissionStaff");
  }

}
