package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class ReceiveTreatmentTrigger_a0_3Signal extends ActorTypeSignal {
  public ReceiveTreatmentTrigger_a0_3Signal() {
    this.setName("ReceiveTreatmentTrigger_a0_3");
    this.setDescription("h");
    this.AddActor("WardStaff");
  }

}
