package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class SignificantCOVIDContactTrigger_p_0Signal extends ActorTypeSignal {
  public SignificantCOVIDContactTrigger_p_0Signal() {
    this.setName("SignificantCOVIDContactTrigger_p_0");
    this.setDescription("SecondPlaceholderSignal");
    this.AddActor("CubicleNurse");
  }

}
