package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.utilities.Distribution;
import java.util.HashMap;
import java.util.Map;

public class TreatmentTimeDistribution_0 {
  protected Distribution<Integer> processingTimeDistribution;
  protected static TreatmentTimeDistribution_0 instance;

  private TreatmentTimeDistribution_0() {
    HashMap<Integer, Double> returnMap = new HashMap<Integer, Double>();
    double TotalOccurances = 3;
    returnMap.put(4320, ((Double) (1 / TotalOccurances)));
    returnMap.put(21600, ((Double) (1 / TotalOccurances)));
    processingTimeDistribution = new Distribution<Integer>((Map) returnMap);
  }

  public static TreatmentTimeDistribution_0 getInstance() {
    if (instance == null) {
      instance = new TreatmentTimeDistribution_0();
    }
    return instance;
  }

  public Integer getProcessingTime() {
    if (processingTimeDistribution == null) {
      return 0;
    } else {
      return processingTimeDistribution.sample();
    }
  }

}
