package EDLanguage.sandbox;

/*Generated by MPS */

import edHello.Signals.Signal;

public class AllActorsCanReceiveSignal extends Signal {

  public AllActorsCanReceiveSignal() {
    this.setName("AllActorsCanReceive");
    this.setDescription("ssss");
    this.AddActor("Staff");
    this.AddActor("Doctor");
    this.AddActor("ENP");
  }
}
