package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class PatientArrivesTrigger_o_0Signal extends ActorTypeSignal {
  public PatientArrivesTrigger_o_0Signal() {
    this.setName("PatientArrivesTrigger_o_0");
    this.setDescription("SecondPlaceholderSignal");
    this.AddActor("TriageNurse");
  }

}
