package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class ESaaTrigger_aSignal extends ActorTypeSignal {
  public ESaaTrigger_aSignal() {
    this.setName("ESaaTrigger_a");
    this.setDescription("h");
    this.AddActor("CubicleNurse");
  }

}
