package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.basicStructures.RoomType;

public class RedAdmissionBay extends RoomType {
  private static RedAdmissionBay instance;

  private RedAdmissionBay() {
    super();
  }

  public static RoomType getInstance() {
    if (instance == null) {
      instance = new RedAdmissionBay();
    }
    return instance;
  }
}
