package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class AdmittoAmberBayTriggerSignal extends ActorTypeSignal {
  public AdmittoAmberBayTriggerSignal() {
    this.setName("AdmittoAmberBayTrigger");
    this.setDescription("h");
    this.AddActor("Doc");
  }

}
