package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.basicStructures.RoomType;

public class MinorsDesk extends RoomType {
  private static RoomType instance;

  private MinorsDesk() {
    super();
  }

  public static RoomType getInstance() {
    if (instance == null) {
      instance = new MinorsDesk();
    }
    return instance;
  }
}
