package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.basicStructures.AgentGenerator;
import repast.simphony.space.continuous.ContinuousSpace;
import repast.simphony.space.grid.Grid;
import repast.simphony.context.Context;
import repast.simphony.engine.schedule.ScheduledMethod;
import simcore.basicStructures.Board;
import simcore.basicStructures.ToolBox;
import simcore.Signals.Signal;
import simcore.Signals.ActorTypeSignal;
import repast.simphony.random.RandomHelper;
import repast.simphony.engine.environment.RunEnvironment;
import java.util.HashMap;

public class patientGenerator_1 extends AgentGenerator {
  public patientGenerator_1(ContinuousSpace<Object> space, Grid<Object> grid, Context<Object> context) {
    super(space, grid, context);
    spawnRoomType = MainEntrance.getInstance();
    initialiseArrivalMap();
  }

  @ScheduledMethod(start = 1, interval = 1)
  public void step() {
    tick();
  }

  public Object onGenerate() {
    patient a = new patient(space, grid, context);
    Board b = new ToolBox(this).ReadBoard();

    Signal sendSignalTemp = new ActorTypeSignal();

    sendSignalTemp.setName("PatientArrivesTrigger_k");
    sendSignalTemp.AddData("patient", a);
    sendSignalTemp.AddActor("TriageNurse");


    // For each agent attribute
    // For each attribute value option
    // Assign the value based on probability function
    double rndDouble = RandomHelper.nextDouble();

    this.generateAttribute_a(a);
    this.generateAttribute_b(a);
    this.generateAttribute_c(a);

    b.PushMission(sendSignalTemp);

    return a;
  }

  public void generateAttribute_a(patient agent) {
    double rndDouble = RandomHelper.nextDouble();

    double runningTotal = 0;

    runningTotal = (RunEnvironment.getInstance().getParameters().getDouble("Strep A PatientsStrepAInfectionStatusSusceptible"));
    if (rndDouble < (runningTotal / 100)) {
      agent.StrepAInfectionStatus = "Susceptible";
      return;
    }
    if (rndDouble < ((RunEnvironment.getInstance().getParameters().getDouble("Strep A PatientsStrepAInfectionStatusAsymptomatic") + runningTotal) / 100)) {
      agent.StrepAInfectionStatus = "Asymptomatic";
      runningTotal += RunEnvironment.getInstance().getParameters().getDouble("Strep A PatientsStrepAInfectionStatusAsymptomatic");
      return;
    } else {
      runningTotal += RunEnvironment.getInstance().getParameters().getDouble("Strep A PatientsStrepAInfectionStatusAsymptomatic");
    }
    if (rndDouble < ((RunEnvironment.getInstance().getParameters().getDouble("Strep A PatientsStrepAInfectionStatusSymptomatic") + runningTotal) / 100)) {
      agent.StrepAInfectionStatus = "Symptomatic";
      runningTotal += RunEnvironment.getInstance().getParameters().getDouble("Strep A PatientsStrepAInfectionStatusSymptomatic");
      return;
    } else {
      runningTotal += RunEnvironment.getInstance().getParameters().getDouble("Strep A PatientsStrepAInfectionStatusSymptomatic");
    }

  }
  public void generateAttribute_b(patient agent) {
    double rndDouble = RandomHelper.nextDouble();

    double runningTotal = 0;

    runningTotal = (RunEnvironment.getInstance().getParameters().getDouble("Strep A PatientsSeveritymoderate"));
    if (rndDouble < (runningTotal / 100)) {
      agent.Severity = "moderate";
      return;
    }
    if (rndDouble < ((RunEnvironment.getInstance().getParameters().getDouble("Strep A PatientsSeveritysevere") + runningTotal) / 100)) {
      agent.Severity = "severe";
      runningTotal += RunEnvironment.getInstance().getParameters().getDouble("Strep A PatientsSeveritysevere");
      return;
    } else {
      runningTotal += RunEnvironment.getInstance().getParameters().getDouble("Strep A PatientsSeveritysevere");
    }
    if (rndDouble < ((RunEnvironment.getInstance().getParameters().getDouble("Strep A PatientsSeveritylow") + runningTotal) / 100)) {
      agent.Severity = "low";
      runningTotal += RunEnvironment.getInstance().getParameters().getDouble("Strep A PatientsSeveritylow");
      return;
    } else {
      runningTotal += RunEnvironment.getInstance().getParameters().getDouble("Strep A PatientsSeveritylow");
    }

  }
  public void generateAttribute_c(patient agent) {
    double rndDouble = RandomHelper.nextDouble();

    double runningTotal = 0;

    runningTotal = (RunEnvironment.getInstance().getParameters().getDouble("Strep A PatientsadmissionRouteEmergencyAttendance"));
    if (rndDouble < (runningTotal / 100)) {
      agent.admissionRoute = "EmergencyAttendance";
      return;
    }

  }

  public void initialiseArrivalMap() {
    ArrivalPerHour = new HashMap<Integer, Integer>();
    ArrivalPerHour.put(1, 0);
    ArrivalPerHour.put(2, 0);
    ArrivalPerHour.put(3, 0);
    ArrivalPerHour.put(4, 0);
    ArrivalPerHour.put(5, 0);
    ArrivalPerHour.put(6, 0);
    ArrivalPerHour.put(7, 3);
    ArrivalPerHour.put(8, 3);
    ArrivalPerHour.put(9, 3);
    ArrivalPerHour.put(10, 3);
    ArrivalPerHour.put(11, 3);
    ArrivalPerHour.put(12, 3);
    ArrivalPerHour.put(13, 4);
    ArrivalPerHour.put(14, 4);
    ArrivalPerHour.put(15, 5);
    ArrivalPerHour.put(16, 4);
    ArrivalPerHour.put(17, 5);
    ArrivalPerHour.put(18, 4);
    ArrivalPerHour.put(19, 0);
    ArrivalPerHour.put(20, 0);
    ArrivalPerHour.put(21, 0);
    ArrivalPerHour.put(22, 0);
    ArrivalPerHour.put(23, 0);
    ArrivalPerHour.put(24, 0);



  }
}
