package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class PatientArrivesTrigger_bSignal extends ActorTypeSignal {
  public PatientArrivesTrigger_bSignal() {
    this.setName("PatientArrivesTrigger_b");
    this.setDescription("SecondPlaceholderSignal");
    this.AddActor("TriageNurse");
  }

}
