package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class ActionTwoTriggerSignal extends ActorTypeSignal {
  public ActionTwoTriggerSignal() {
    this.setName("ActionTwoTrigger");
    this.setDescription("h");
    this.AddActor("Doc");
  }

}
