package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.Signal;

public class PatientWaitingForMajorsSignal extends Signal {

  public PatientWaitingForMajorsSignal() {
    this.setName("PatientWaitingForMajors");
    this.setDescription("Patient is waiting to go to Majors to be triaged there");
    this.AddActor("MajorsTriageNurse");
  }
}
