package EDLanguage.sandbox;

/*Generated by MPS */

import edHello.agents.Actor;
import repast.simphony.space.continuous.ContinuousSpace;
import repast.simphony.space.grid.Grid;
import edHello.Signals.Signal;

public class Staff extends Actor {

  public double groupStress = Double.parseDouble("" + "0");

  public Staff(ContinuousSpace<Object> space, Grid<Object> grid) {
    super(space, grid);
  }


  public void SetMission(Signal s) {
    switch (s.getName()) {
      case "":
        break;
      default:
        System.out.println("Set mission: " + s.getName() + " failed!");
        return;
    }
    curActionStep = 0;
  }


}
