package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class TakeabedTrigger_cSignal extends ActorTypeSignal {
  public TakeabedTrigger_cSignal() {
    this.setName("TakeabedTrigger_c");
    this.setDescription("h");
    this.AddActor("WardStaff");
  }

}
