package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.Signals.ActorTypeSignal;

public class AdmittosideroomTrigger_a3Signal extends ActorTypeSignal {
  public AdmittosideroomTrigger_a3Signal() {
    this.setName("AdmittosideroomTrigger_a3");
    this.setDescription("h");
    this.AddActor("Doctor");
  }

}
