package EDLanguage.sandbox;

/*Generated by MPS */

import simcore.basicStructures.Resource;

public class LateralFlowTest extends Resource {
  private static LateralFlowTest instance;

  private LateralFlowTest() {
    super();
  }

  public static LateralFlowTest getInstance() {
    if (instance == null) {
      instance = new LateralFlowTest();
    }
    return instance;
  }
}
